### ISSUE TITLE
Error in the example of using the LimitOutput parameter

### ISSUE THREAD

**Issue by true-alex** [pmqs/Compress-Raw-Zlib#21]
The inner loop must be repeated as long as the Z_BUF_ERROR status is set.
The Z_BUF_ERROR status means that Zlib has more data to output, but the size of the output variable has already reached the maximum allowed size. In this case, you need to re-call inflate without adding anything to the input.

The example says this:
`} while ($status == Z_OK && length $input);`
but that's not true it should be
`} while ($status == Z_BUF_ERROR && length $input);`
![изображение](https://user-images.githubusercontent.com/68057876/234829545-89ce47a7-f255-4796-8655-f1aa4151e511.png)

**Comment by pmqs** [comment]
Hey @true-alex - - sorry for the delay in responding.

Good catch! Looking at this I initially didn't think there was an error at all, but I crafted some code that triggered an error with the code in the example

Thinking about this some more, rather than using 

    while ($status == Z_BUF_ERROR && length $input);

I will use this for the loop condition

    while length $input;

Below are quotes from the `inflate` section of the  of the [zlib manual](https://zlib.net/manual.html)

> inflate() returns Z_OK if some progress has been made (more input processed or more output produced)
>...
> Z_BUF_ERROR if no progress was possible

The two return code `Z_OK` and `Z_BUF_ERROR` look like they are possible in that inner while loop, and are already tested for.

**Comment by pmqs** [comment]
Fixed in version 2.205 which is now uploaded to [CPAN ](https://metacpan.org/dist/Compress-Raw-Zlib).
